apiVersion: v1
kind: Service
metadata:
  name: bchd
  namespace: default
spec:
  ports:
    - port: 8456
      targetPort: 8456
  selector:
    service: bchd
  type: LoadBalancer
  externalTrafficPolicy: Local
